// 해당프로젝트는 shadcn/ui 라이브러리를 사용합니다. (https://ui.shadcn.com/docs/installation)
// shadcn/ui 라이브러리는 Tailwind CSS 기반으로 제작되었습니다.
// 따라서 Tailwind CSS가 프로젝트에 설정되어 있어야 합니다.
// shadcn/ui 설치 및 Tailwind CSS 설정이 완료되었다고 가정하고 작성된 코드입니다.
// 아이콘은 lucide-react 라이브러리를 사용합니다. (https://lucide.dev/)

import '@/styles/custom-shadcn.css';
import '@/styles/global.css';

// Toaster (sonner)
import { Toaster } from 'sonner';

import ModalProvider from '@/components/modal/ModalProvider';

export const metadata = {
  title: 'CompCare',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <ModalProvider>{children}</ModalProvider>

        {/* Toast 전역 렌더링 */}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
