import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/global.css';
import '@/styles/custom-prime.css';

//primereact
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/lara-light-green/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';

import ModalProvider from '@/components/modal/ModalProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: '프로젝트명',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrimeReactProvider>
          <ModalProvider>{children}</ModalProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
